### ISSUE TITLE
i have problem

### ISSUE THREAD

**Issue by amirlime** [RainyXeon/Cylane#46]
![image](https://github.com/RainyXeon/Cylane/assets/122648967/2e30f824-435a-430c-ade2-2ad7905b465d)
![image](https://github.com/RainyXeon/Cylane/assets/122648967/3ed7db9f-e4be-4cf8-9ec1-b3630ca0f8f5)
![image](https://github.com/RainyXeon/Cylane/assets/122648967/0c6a9116-1505-43cd-8d10-8a76c7d746b3)
and i have no slash commands

**Comment by RainyXeon** [comment]
@amirlime 
There're 2 modules that not loaded is autodeploy and lavalink. The first one need the ready.js event loaded after successful dealing a connection with discord api server.

The second one need some time for bot dealing a connection with lavalink server. Once you see a `Lavalink "nodename" connected`, your bot successfully connected.

Otherwise, you can use `node deploySlash.js global` for manualy deploy slash to discord server.

**Comment by RainyXeon** [comment]
@amirlime Long db load issue now fixed in commit ca44224a0d507237b5f31caafc881db0319d49ab

https://github.com/RainyXeon/Cylane/tree/ca44224a0d507237b5f31caafc881db0319d49ab
